repo: http://github.com/eshoo/kittenStuffs
services:
  - frontend:
      install_script:
        - npm install .
      test_script:
        - npm test
      language: nodejs
      nodejs:
        - 0.10
      propeller:
        ports:
          FRONTEND_HTTP: 8000 
          MYSQL: 3306
        services:
          - postgres
  - backend:
      language: nodejs
      propeller:
        instances: 1
